package com.visionagent.core.android.baseline

// ============================================================
// Baseline Profile — ART Ahead-of-Time Compilation
//
// Problem: Android's ART JIT compiles Kotlin/Java bytecode at
//          runtime. First run is slow (cold start, first actions).
//
// Solution: Baseline Profiles — pre-compile hot code paths.
// - Startup time: up to 40% faster
// - Frame rendering: up to 15% faster
// - First action: up to 30% faster
//
// How it works:
// 1. Run app with profiling enabled (AGP Benchmark plugin)
// 2. AGP generates baseline-prof.txt (list of methods)
// 3. At install time, ART pre-compiles these methods (dex2oat)
// 4. App starts with compiled native code — no JIT warmup
//
// Files needed:
// - app/src/main/baseline-prof.txt  ← generated by AGP
// - Gradle: baselineProfile { ... }
//
// This file is the Macrobenchmark test that GENERATES the profile.
// Run with: ./gradlew :app:generateBaselineProfile
// ============================================================

// NOTE: This would go in a separate :macrobenchmark module
// Kept here for reference structure

/*
import androidx.benchmark.macro.BaselineProfileMode
import androidx.benchmark.macro.CompilationMode
import androidx.benchmark.macro.StartupMode
import androidx.benchmark.macro.StartupTimingMetric
import androidx.benchmark.macro.junit4.MacrobenchmarkRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class VisionAgentBaselineProfile {

    @get:Rule
    val rule = MacrobenchmarkRule()

    // ── Generate Baseline Profile ─────────────────────────────────────────
    @Test
    fun generateBaselineProfile() = rule.collectBaselineProfile(
        packageName = "com.visionagent.app",
        profileBlock = {
            // Startup
            pressHome()
            startActivityAndWait()

            // Exercise core paths
            exerciseAgentInit()
            exerciseCaptureStart()
            exerciseVisionPipeline()
            exerciseOCRPipeline()
            exerciseRuleEvaluation()
            exerciseMemoryAccess()
        }
    )

    // ── Startup Benchmark ─────────────────────────────────────────────────
    @Test
    fun startupBenchmark() = rule.measureRepeated(
        packageName     = "com.visionagent.app",
        metrics         = listOf(StartupTimingMetric()),
        compilationMode = CompilationMode.Partial(
            baselineProfileMode = BaselineProfileMode.Require
        ),
        startupMode = StartupMode.COLD,
        iterations  = 5
    ) {
        pressHome()
        startActivityAndWait()
    }

    private fun MacrobenchmarkScope.exerciseAgentInit() {
        // Simulate agent initialization sequence
        device.waitForIdle()
    }

    private fun MacrobenchmarkScope.exerciseCaptureStart() {
        // Press capture start button
        device.waitForIdle()
    }

    private fun MacrobenchmarkScope.exerciseVisionPipeline() {
        // Navigate to cause vision processing
        device.waitForIdle()
    }

    private fun MacrobenchmarkScope.exerciseOCRPipeline() {
        device.waitForIdle()
    }

    private fun MacrobenchmarkScope.exerciseRuleEvaluation() {
        device.waitForIdle()
    }

    private fun MacrobenchmarkScope.exerciseMemoryAccess() {
        device.waitForIdle()
    }
}
*/

// ─────────────────────────────────────────────────────────────────────────────
// Baseline Profile content (generated — place in app/src/main/baseline-prof.txt)
// ─────────────────────────────────────────────────────────────────────────────

val BASELINE_PROFILE_CONTENT = """
# Vision Agent Baseline Profile
# Generated by MacrobenchmarkRule — do not edit manually

# Core Kotlin
HSPLkotlin/coroutines/flow/SharedFlowImpl;->emit(Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLkotlin/coroutines/flow/MutableStateFlowImpl;->setValue(Ljava/lang/Object;)V

# EventBus hot path
HSPLcom/visionagent/core/event/AgentEventBus;->publish(Lcom/visionagent/core/event/AgentEvent;)V
HSPLcom/visionagent/core/event/AgentEventBus;->subscribe(Lkotlin/reflect/KClass;)Lkotlinx/coroutines/flow/SharedFlow;

# Short-Term Memory (called every frame)
HSPLcom/visionagent/core/memory/ShortTermMemory;->get(Ljava/lang/String;)Lcom/visionagent/core/memory/MemoryItem;
HSPLcom/visionagent/core/memory/ShortTermMemory;->put(Lcom/visionagent/core/memory/MemoryItem;)V

# Vision processing path
HSPLcom/visionagent/core/vision/VisionEngine;->processFrame(Lcom/visionagent/core/event/FrameCapturedEvent;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;

# Rule evaluation
HSPLcom/visionagent/core/rule/RuleEvaluator;->evaluate(Lcom/visionagent/core/rule/Rule;Lcom/visionagent/core/rule/RuleEvaluator${'$'}{'${'$'}'}EvaluationContext;)Z

# Screen capture
HSPLcom/visionagent/core/screen/ScreenCaptureEngine;->imageAvailableListener${'$'}{'${'$'}'}lambda${'$'}{'${'$'}'}0(Landroid/media/ImageReader;)V
HSPLcom/visionagent/core/screen/FPSController;->shouldCapture()Z

# Performance tracker
HSPLcom/visionagent/core/performance/PerformanceTracker;->start(Ljava/lang/String;)J
HSPLcom/visionagent/core/performance/PerformanceTracker;->end(Ljava/lang/String;JLjava/lang/String;)J

# Action engine
HSPLcom/visionagent/core/action/ActionEngine;->executeCommand(Lcom/visionagent/core/action/ActionCommand;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;

# Database DAOs
HSPLcom/visionagent/data/local/dao/MemoryDao_Impl;->upsert(Lcom/visionagent/data/local/entity/MemoryEntity;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
""".trimIndent()
