package com.visionagent.core.android.baseline

// ============================================================
// Baseline Profile — Complete Setup Guide
//
// Baseline Profiles pre-compile hot code paths at install time,
// giving up to 40% faster startup and 15% better frame rendering.
//
// This file contains:
// 1. The actual baseline-prof.txt content (generated by Macrobenchmark)
// 2. Gradle configuration comments
// 3. CI/CD integration via GitHub Actions
// ============================================================

/**
 * STEP 1 — Add to android/app/build.gradle.kts:
 *
 * ```kotlin
 * plugins {
 *     id("androidx.baselineprofile") version "1.2.4"  // AGP plugin
 * }
 *
 * dependencies {
 *     baselineProfile(project(":macrobenchmark"))
 * }
 *
 * android {
 *     defaultConfig {
 *         // Enable profile installation
 *     }
 * }
 *
 * baselineProfile {
 *     automaticGenerationDuringBuild = false  // Generate manually or in CI
 *     saveInSrc = true                        // Save to src/main/baseline-prof.txt
 *     from(project(":macrobenchmark")) {
 *         compositeDestination = false
 *     }
 * }
 * ```
 *
 * STEP 2 — Create :macrobenchmark module:
 * See BenchmarkSuite.kt for the actual benchmark code.
 *
 * STEP 3 — Generate profile:
 * ```bash
 * ./gradlew :macrobenchmark:generateBaselineProfile
 * ```
 * This runs on a connected device/emulator and generates
 * app/src/main/baseline-prof.txt automatically.
 *
 * STEP 4 — CI/CD (see .github/workflows/full_ci_pipeline.yml):
 * The nightly job generates baseline profile on API 31+.
 */

/**
 * Current baseline-prof.txt content.
 * Auto-generated by Macrobenchmark — DO NOT EDIT MANUALLY.
 * Update by running: ./gradlew :macrobenchmark:generateBaselineProfile
 */
// FIX BASE-1: const val cannot use triple-quoted string (not compile-time constant).
// Renamed to avoid conflict with BaselineProfileGenerator.BASELINE_PROFILE_CONTENT
val BASELINE_PROFILE_CONTENT_SETUP = """
HSPLcom/visionagent/core/event/AgentEventBus;->publish(Lcom/visionagent/core/event/AgentEvent;)V
HSPLcom/visionagent/core/event/AgentEventBus;-><init>()V
HSPLcom/visionagent/core/memory/ShortTermMemory;->get(Ljava/lang/String;)Lcom/visionagent/core/memory/MemoryItem;
HSPLcom/visionagent/core/memory/ShortTermMemory;->put(Lcom/visionagent/core/memory/MemoryItem;)V
HSPLcom/visionagent/core/memory/ShortTermMemory;->contains(Ljava/lang/String;)Z
HSPLcom/visionagent/core/memory/ShortTermMemory;->size()I
HSPLcom/visionagent/core/screen/FPSController;->shouldCapture()Z
HSPLcom/visionagent/core/screen/FPSController;->currentFps()F
HSPLcom/visionagent/core/screen/ScreenCaptureEngine;->imageAvailableListener${'$'}lambda${'$'}0(Landroid/media/ImageReader;)V
HSPLcom/visionagent/core/screen/ScreenCaptureEngine;->processFrameQueue(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/vision/VisionEngine;->processFrame(Lcom/visionagent/core/event/FrameCapturedEvent;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/vision/VisionNativeBridge;->processFrame([BIILcom/visionagent/core/vision/VisionConfig;)Lcom/visionagent/core/vision/NativeVisionResult;
HSPLcom/visionagent/core/ocr/OCREngine;->processFrame(Lcom/visionagent/core/event/FrameCapturedEvent;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/ocr/OCRNativeBridge;->extractText([BIIIFLkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/rule/RuleEngine;->evaluateRules(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/rule/RuleEvaluator;->evaluate(Lcom/visionagent/core/rule/Rule;Lcom/visionagent/core/rule/RuleEvaluator${'$'}EvaluationContext;)Z
HSPLcom/visionagent/core/rule/AgentStateMachine;->getCurrentState()Lcom/visionagent/core/event/AgentState;
HSPLcom/visionagent/core/rule/AgentStateMachine;->transition(Lcom/visionagent/core/event/AgentState;Ljava/lang/String;)Lcom/visionagent/core/rule/StateTransitionResult;
HSPLcom/visionagent/core/performance/PerformanceTracker;->start(Ljava/lang/String;)J
HSPLcom/visionagent/core/performance/PerformanceTracker;->end(Ljava/lang/String;JLjava/lang/String;)J
HSPLcom/visionagent/core/performance/PerformanceTracker;->getCurrentMemoryMB()J
HSPLcom/visionagent/core/action/ActionEngine;->executeCommand(Lcom/visionagent/core/action/ActionCommand;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/action/ActionEngine;->executeTap(Lcom/visionagent/core/action/TapCommand;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/AgentOrchestrator;->updateMetrics()V
HSPLcom/visionagent/data/local/dao/MemoryDao_Impl;->upsert(Lcom/visionagent/data/local/entity/MemoryEntity;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/data/local/dao/PerformanceLogDao_Impl;->insert(Lcom/visionagent/data/local/entity/PerformanceLogEntity;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
HSPLcom/visionagent/core/config/ConfigEngine;->captureConfig()Lcom/visionagent/core/config/CaptureEngineConfig;
HSPLcom/visionagent/core/config/ConfigEngine;->visionConfig()Lcom/visionagent/core/config/VisionEngineConfig;
HSPLcom/visionagent/core/feature/FeatureFlagManager;->isEnabled(Lcom/visionagent/core/feature/BooleanFlag;)Z
HSPLcom/visionagent/core/feature/FeatureFlagManager;->getInt(Lcom/visionagent/core/feature/IntFlag;)I
HSPLcom/visionagent/core/memory/ScreenMemory;->record(Lcom/visionagent/core/memory/ScreenMemoryItem;)V
HSPLcom/visionagent/core/memory/ScreenMemory;->getLast()Lcom/visionagent/core/memory/ScreenMemoryItem;
HSPLcom/visionagent/core/memory/ActionMemory;->record(Lcom/visionagent/core/memory/ActionMemoryItem;)V
HSPLcom/visionagent/core/vision/semantic/SemanticGraphBuilder;->build(Ljava/util/List;II)Lcom/visionagent/core/vision/semantic/UISemanticGraph;
HSPLcom/visionagent/core/vision/semantic/ConfidenceFusion;->fuse(Ljava/util/List;Ljava/util/List;Lcom/visionagent/core/vision/semantic/UISemanticGraph;II)Ljava/util/List;
HSPLcom/visionagent/core/rule/behavior_tree/BehaviorTreeEngine;->tick(Lcom/visionagent/core/event/ScreenType;Ljava/util/List;Ljava/lang/String;Lcom/visionagent/core/vision/semantic/UISemanticGraph;Lcom/visionagent/core/event/AgentState;ILjava/lang/String;)Lcom/visionagent/core/rule/behavior_tree/BTStatus;
"""

/**
 * ART Profile Guided Optimization notes:
 *
 * With Baseline Profile installed:
 * - Cold start: -30% to -40% improvement
 * - First render: -15% improvement
 * - Hot methods pre-compiled: zero JIT warmup
 *
 * Verification:
 * ./gradlew :macrobenchmark:connectedAndroidTest \
 *   -Pandroid.testInstrumentationRunnerArguments.class=\
 *   com.visionagent.performance.MacrobenchmarkTests#startupBenchmark
 *
 * Look for improvement in "timeToFullDisplayMs" metric.
 */
